### ISSUE TITLE
ImportError: No module named encoding

### ISSUE THREAD

**Issue by maxcado** [1200wd/bitcoinlib#71] opened 2019-01-04 06:32 UTC
So far the only thing that seems to work upon installing this library is the cli-wallet functions. However, when attempting to use other functions of the wallet in the python environment I get nothing but module errors. For instance with from bitcoinlib.wallets import bitcoinlib the following error message comes up:
 File "/user/home/.local/python2.7/site-packages/bitcoinlib/bitcoinlib/_init_.py" line 20, <module>
import bitcoinlib.encoding
ImportError: No module named encoding

Please advise as to how to rectify this module error.

**Comment by mccwdev** [comment] 2019-01-04 13:45
Did you install the library with pip?  And are you using the same Python interpreter when installing and running?

**Comment by maxcado** [comment] 2019-01-05 22:48
I installed the library from source build not pip. It was installed in python 2.7 site-packages. The default interpreter at command line is also python 2.7 so it looks like I'm using the same interpreter as it was installed. This is a linux machine with Ubuntu Bionic linux mint. But note that I'm having the same 'module_encoding' issues on a windows machine as well.

**Comment by mccwdev** [comment] 2019-01-08 15:18
Python could not find the library path. You need to add the path to the library to the python environment or run python from the bitcoinlib directory

**Comment by mccwdev** [comment] 2019-01-08 15:41
I need to look into the includes, not sure if there is an error, but I got some errors as well on a fresh install.

**Comment by mccwdev** [comment] 2019-03-06 12:15
I was not able to reproduce this issue anymore, tried on a couple of different machines with the following commands:

    $ git clone https://github.com/1200wd/bitcoinlib.git
    $ cd bitcoinlib
    $ pip install -r docs/requirements.txt

If you still encounter this problem please let me know, but for now I close it.

**Closed by mccwdev** 2019-03-06 12:15 UTC
Labels: bug
