### ISSUE TITLE
Unconfirmed Transactions

### ISSUE THREAD

**Issue by Fasdgfdzv** [1200wd/bitcoinlib#162] opened 2021-02-18 12:34 UTC
I have multiple unconfirmed transactions using ```send``` and ```send_to```. I got TBTC from a faucet which took a few minutes, and the second one is the bitcoin from the faucet to another address in my wallet, which is taking more than a day. 
```
Confirmed Transaction:
block_height: 1936543
size: 225
confirmations: 35
fee: 144
status: confirmed
input_total: 2839231
output_total: 2839087
network_name: testnet
verified: False


Unconfirmed Transaction:
block_height: None
size: 223
confirmations: 0
fee: 549
status: unconfirmed
input_total: 10000
output_total: 9451
network_name: testnet
verified: False
```
Why isn't the transactions confirming? How do I stop broadcasting the transaction and remove it from the network?

**Comment by Fasdgfdzv** [comment] 2021-02-20 11:59
I checked the mempool and I can't find my transactions, though after doing `scan` and `update_transactions`, my wallet is still showing there is unconfirmed transactions.

**Comment by mccwdev** [comment] 2021-02-20 15:58
At the moment you can not easily delete a transaction from a wallet because of unwanted side effects. But maybe in this case it would be handy to be able too remove unconfirmed transactions. 

The only way to fix this now is to delete the wallet (with wallet_empty or wallet_delete method) and recreate it.

But normally you shouldn't be able to create a testnet transaction with the library which will never be confirmed. Do you have any idea what caused the problem?

**Comment by Fasdgfdzv** [comment] 2021-02-27 04:02
I have reproduced the issue doing `w.send([("address",2000)],[(w.utxos()[0]['txid'],w.utxos()[0]['output_n'],w.utxos()[0]['key_id'],w.utxos()[0]['value'])])`

**Comment by mccwdev** [comment] 2021-03-13 21:04
I think this should be fixed in commit https://github.com/1200wd/bitcoinlib/commit/9cac80e24a88d9b3c30c21fa5ddad293e09ebae7 and other commits in the latest branch

**Closed by mccwdev** 2021-03-13 21:04 UTC
Labels: bug, enhancement
